### PR TITLE
Added config() functionality

### PR DESCRIPTION
**Pull request by bastihilger**
Hi - I don't know if you want to use this or not. It's just something that I use pretty often, and since you already have a "twig extensions" plugin out there, I thought there is no need for me to make a plugin just for this simple addition.
But if for some reason you think this makes no sense, please let me know ;-)

### CODE REVIEW

**Comment by vojtasvoboda** [comment]
Ok, seems good to me. Could you please add _default_ parameter to the filter? To be compatible with _config_ function:

`function config($key = null, $default = null)`

And also add 'Function' suffix to getter: `getConfigFunction()`, as other functions.

Thanks!

**Comment by vojtasvoboda** [comment]
I also will appreciate if you add a new section to Readme file and add small unit test, just with creating new config key, read config from template and assert when they are equal (you can copy it from another existing unit test). Would it be possible, please? I will be online whole day, so I can help you if you get lost :-)

**Comment by bastihilger** [comment]
Will do when i'm back from lunch ;-)

**Comment by vojtasvoboda** [comment]
Thank you very much :-) Let me know how it works.

**Comment by bastihilger** [comment]
I am kind of stuck at unit testing. When I run phpunit at root level it only seems to run the core test, but not the plugin test. Could not find any reason for that so far - how do I run the unit tests for the plugin?

**Comment by bastihilger** [comment]
btw. I ran october:up and the plugin is working.

**Comment by bastihilger** [comment]
Forget it - I found it, it was a wrong alias in my homestead configuration for "phpunit"

**Comment by bastihilger** [comment]
OK, the unit test passed, I added the default values and changed the Readme. Hope it's OK like this.

**Comment by bastihilger** [comment]
Damn, I just saw that a composer.lock file slipped into the commit. Is that a problem?

**Comment by vojtasvoboda** [comment]
New version is available as update 1.0.5. Would you mind to test it please?

**Comment by bastihilger** [comment]
Tested and worked as expected. Thanks!

**Comment by vojtasvoboda** [comment]
Thanks for this new feature and testing :-)

**Pull request merged**
