### PR TITLE
Added redirect function {{ redirect("https://m.web.com") }}

### PR DESCRIPTION
**Pull request by LucasZdv**
I added the redirect function to twig, it is already tested and it works correctly.

### CODE REVIEW

**Comment by vojtasvoboda** [comment]
Do you think is it function, that should be in template? I usually place redirects to the controllers.

**Comment by LucasZdv** [comment]
Of course, but in some cases it is helpful to be able to do it from the template, I have two cases in which it has served me.
Redirect to a thankyou page, and to a subdomain when a device is recognized as a mobile phone. Feel free to reject it if you want, I can make a specific plugin for this.

**Comment by vojtasvoboda** [comment]
How do you check mobile devices? I usually check it in the controller:

```
use Jenssegers\Agent\Agent as Agent;
$agent = new Agent();
...
return $agent->isMobile() ? Redirect::to('/mobile-thanks') : Redirect::to('/thanks');
```

**Comment by LucasZdv** [comment]
I do it in the layout. 
`
{% if Agent.isPhone() or Agent.isTablet()%}`

**Comment by vojtasvoboda** [comment]
Ok. Could you please fix this typo: https://travis-ci.org/vojtasvoboda/oc-twigextensions-plugin/jobs/525405110 to make Travis CI pass and add two unit tests here: https://github.com/vojtasvoboda/oc-twigextensions-plugin/blob/master/tests/PluginTest.php (one test with empty URL and one test with valid URL). Thanks

**Comment by daftspunk** [comment]
There is a redirect function included in v3 now:

https://docs.octobercms.com/3.x/markup/function/redirect.html

This can probably be closed.

**Pull request closed without merging**
